name: ${COMPOSE_PROJECT_NAME}

services:
  nginx:
    build: ./docker/nginx/
    container_name: nginx-container

  php:
    build: ./docker/php/
    container_name: php-container

  db:
    image: postgres:12-alpine
    container_name: db-container

networks:
  my-network:
    driver: bridge

volumes:
  pgdata: