name: ${COMPOSE_PROJECT_NAME}

services: 
  nginx:
    build: ./docker/nginx/
  php:
    build: ./docker/php/
  db:
    image: postgres:12-alpine
    
networks:
  my-network:
    driver: bridge

volumes:
  pgdata: