services: 
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./docker:/app/
    depends_on:
      - php
    networks:
      - my-network
  
  php:
    volumes:
      - ./app:/app/
    depends_on:
      - db
    networks:
      - my-network
    user: "1000:1000"
  
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network
